import { CreateAssistantDTO } from "@vapi-ai/web/dist/api";
import { z } from "zod";

export const mappings = {
  "react.js": "react",
  reactjs: "react",
  react: "react",
  "next.js": "nextjs",
  nextjs: "nextjs",
  next: "nextjs",
  "vue.js": "vuejs",
  vuejs: "vuejs",
  vue: "vuejs",
  "express.js": "express",
  expressjs: "express",
  express: "express",
  "node.js": "nodejs",
  nodejs: "nodejs",
  node: "nodejs",
  mongodb: "mongodb",
  mongo: "mongodb",
  mongoose: "mongoose",
  mysql: "mysql",
  postgresql: "postgresql",
  sqlite: "sqlite",
  firebase: "firebase",
  docker: "docker",
  kubernetes: "kubernetes",
  aws: "aws",
  azure: "azure",
  gcp: "gcp",
  digitalocean: "digitalocean",
  heroku: "heroku",
  photoshop: "photoshop",
  "adobe photoshop": "photoshop",
  html5: "html5",
  html: "html5",
  css3: "css3",
  css: "css3",
  sass: "sass",
  scss: "sass",
  less: "less",
  tailwindcss: "tailwindcss",
  tailwind: "tailwindcss",
  bootstrap: "bootstrap",
  jquery: "jquery",
  typescript: "typescript",
  ts: "typescript",
  javascript: "javascript",
  js: "javascript",
  "angular.js": "angular",
  angularjs: "angular",
  angular: "angular",
  "ember.js": "ember",
  emberjs: "ember",
  ember: "ember",
  "backbone.js": "backbone",
  backbonejs: "backbone",
  backbone: "backbone",
  nestjs: "nestjs",
  graphql: "graphql",
  "graph ql": "graphql",
  apollo: "apollo",
  webpack: "webpack",
  babel: "babel",
  "rollup.js": "rollup",
  rollupjs: "rollup",
  rollup: "rollup",
  "parcel.js": "parcel",
  parceljs: "parcel",
  npm: "npm",
  yarn: "yarn",
  git: "git",
  github: "github",
  gitlab: "gitlab",
  bitbucket: "bitbucket",
  figma: "figma",
  prisma: "prisma",
  redux: "redux",
  flux: "flux",
  redis: "redis",
  selenium: "selenium",
  cypress: "cypress",
  jest: "jest",
  mocha: "mocha",
  chai: "chai",
  karma: "karma",
  vuex: "vuex",
  "nuxt.js": "nuxt",
  nuxtjs: "nuxt",
  nuxt: "nuxt",
  strapi: "strapi",
  wordpress: "wordpress",
  contentful: "contentful",
  netlify: "netlify",
  vercel: "vercel",
  "aws amplify": "amplify",
};


export const interviewCovers = [
  "/adobe.png",
  "/amazon.png",
  "/facebook.png",
  "/hostinger.png",
  "/pinterest.png",
  "/quora.png",
  "/reddit.png",
  "/skype.png",
  "/spotify.png",
  "/telegram.png",
  "/tiktok.png",
  "/yahoo.png",
];

export const testDataCards: Interview[] = [
  {
    id: "1",
    userId: "user1",
    role: "Frontend Developer",
    type: "Technical",
    techstack: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    level: "Junior",
    questions: ["What is React?"],
    finalized: false,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "2",
    userId: "user1",
    role: "Full Stack Developer",
    type: "Mixed",
    techstack: ["Node.js", "Express", "MongoDB", "React"],
    level: "Senior",
    questions: ["What is Node.js?"],
    finalized: false,
    createdAt: "2024-03-14T15:30:00Z",
  },
  {
    id: "3",
    userId: "user2",
    role: "Backend Developer",
    type: "Technical",
    techstack: ["Java", "Spring Boot", "MySQL"],
    level: "Mid",
    questions: ["Explain Spring Boot lifecycle."],
    finalized: true,
    createdAt: "2024-03-10T08:45:00Z",
  },
  {
    id: "4",
    userId: "user3",
    role: "Data Scientist",
    type: "Technical",
    techstack: ["Python", "Pandas", "Scikit-learn"],
    level: "Senior",
    questions: ["How do you handle missing data?"],
    finalized: false,
    createdAt: "2024-04-01T12:00:00Z",
  },
  {
    id: "5",
    userId: "user2",
    role: "DevOps Engineer",
    type: "Behavioral",
    techstack: ["Docker", "Kubernetes", "AWS"],
    level: "Mid",
    questions: ["Describe a challenging deployment you handled."],
    finalized: true,
    createdAt: "2024-02-28T09:30:00Z",
  },
  {
    id: "6",
    userId: "user4",
    role: "Mobile Developer",
    type: "Technical",
    techstack: ["Flutter", "Dart"],
    level: "Junior",
    questions: ["What are widgets in Flutter?"],
    finalized: false,
    createdAt: "2024-03-20T14:20:00Z",
  },
  {
    id: "7",
    userId: "user1",
    role: "Product Manager",
    type: "Behavioral",
    techstack: [],
    level: "Senior",
    questions: ["How do you prioritize product features?"],
    finalized: true,
    createdAt: "2024-01-10T11:15:00Z",
  },
  {
    id: "8",
    userId: "user3",
    role: "QA Engineer",
    type: "Technical",
    techstack: ["Selenium", "Jest"],
    level: "Mid",
    questions: ["What is the difference between unit and integration testing?"],
    finalized: false,
    createdAt: "2024-03-18T16:00:00Z",
  },
  {
    id: "9",
    userId: "user5",
    role: "UI/UX Designer",
    type: "Mixed",
    techstack: ["Figma", "Adobe XD"],
    level: "Junior",
    questions: ["How do you gather user feedback?"],
    finalized: true,
    createdAt: "2024-04-05T09:00:00Z",
  },
  {
    id: "10",
    userId: "user4",
    role: "Security Engineer",
    type: "Technical",
    techstack: ["OWASP", "Python", "Linux"],
    level: "Senior",
    questions: ["Explain the OWASP top 10 vulnerabilities."],
    finalized: false,
    createdAt: "2024-03-22T13:45:00Z",
  },
];
